const I18N = {
en: {
  "nav.services": "Services",
  "nav.why": "Why us",
  "nav.gallery": "Gallery",
  "nav.faq": "FAQ",
  "nav.reviews": "Reviews",
  "nav.contact": "Contact",
  "nav.call": "+965 9965 2571",
  "nav.whatsapp": "WhatsApp",
  "hero.kicker": "Hawalli, Kuwait · AC maintenance & repair",
  "hero.title": "Your AC running cold,<br>every single day.",
  "hero.sub": "AC maintenance, repair and installation across Hawalli — open daily 7 AM to 8 PM. Regular servicing that keeps your cooling strong all summer.",
  "hero.cta1": "Book a visit",
  "hero.cta2": "WhatsApp us",
  "trust.t1t": "Open daily",
  "trust.t1d": "7:00 AM – 8:00 PM",
  "trust.t2t": "AC repair · service",
  "trust.t2d": "Split & central systems",
  "trust.t3t": "Hawalli based",
  "trust.t3d": "Serving all of Kuwait",
  "stats.samedayNum": "Open 7 days",
  "stats.sameday": "7 AM – 8 PM daily",
  "stats.tradesNum": "Split &amp; central AC",
  "stats.trades": "maintenance specialists",
  "stats.rateNum": "Same-day visits",
  "stats.rate": "across Hawalli",
  "stats.visitNum": "All major brands",
  "stats.visit": "serviced &amp; repaired",
  "services.kicker": "What we do",
  "services.title": "Installation and repair, done right",
  "services.s1t": "AC repair",
  "services.s1d": "Split and central ACs diagnosed and repaired quickly.",
  "services.s2t": "AC maintenance",
  "services.s2d": "Filters, coils and drains cleaned for maximum cooling.",
  "services.s3t": "AC installation",
  "services.s3d": "New units installed neatly and commissioned correctly.",
  "services.s4t": "Gas refilling",
  "services.s4d": "Refrigerant recharges with leak checks for weak cooling.",
  "services.s5t": "Duct & filter cleaning",
  "services.s5d": "Better airflow and cleaner air through your whole home.",
  "services.s6t": "Annual service plans",
  "services.s6d": "Scheduled maintenance that stops breakdowns before they start.",
  "why.kicker": "Why choose us",
  "why.title": "Open daily, done properly",
  "why.intro": "Your AC runs hardest when you need it most — we are open every day from 7 AM to 8 PM so maintenance and repairs happen on your schedule, not ours.",
  "why.l1t": "Open 7 days a week",
  "why.l1d": "7:00 AM – 8:00 PM daily, including Fridays.",
  "why.l2t": "Hawalli based",
  "why.l2d": "Fast visits across Hawalli and Kuwait City.",
  "why.l3t": "Upfront pricing",
  "why.l3d": "You approve the price before we begin — no surprises.",
  "why.l4t": "WhatsApp booking",
  "why.l4d": "Message us on +965 9965 2571 — send a photo of your unit.",
  "gallery.kicker": "Our work",
  "gallery.title": "Neat work, done properly",
  "gallery.c1": "Outdoor units cleaned and serviced",
  "gallery.c2": "Indoor units tested for cold airflow",
  "gallery.c3": "New units installed on rooftops",
  "reviews.kicker": "What people say",
  "reviews.title": "Trusted across Hawalli",
  "reviews.more": "Find us on Google — see our location and reviews",
  "faq.kicker": "Good to know",
  "faq.title": "Frequently asked questions",
  "faq.q1": "What are your opening hours?",
  "faq.a1": "We are open every day, 7:00 AM to 8:00 PM, including Fridays.",
  "faq.q2": "Which areas do you serve?",
  "faq.a2": "We are based in Hawalli and serve homes and offices across Kuwait.",
  "faq.q3": "Do you give quotes before starting?",
  "faq.a3": "Yes — you approve the price before we begin any work. No surprises.",
  "faq.q4": "How do I book a visit?",
  "faq.a4": "Call or WhatsApp us on +965 9965 2571 — tell us the unit type and the problem.",
  "contact.kicker": "Get in touch",
  "contact.title": "Book your visit",
  "contact.addr": "Address",
  "contact.phone": "Phone",
  "contact.hours": "Hours",
  "contact.hoursVal": "Daily: 7:00 AM – 8:00 PM | Open 7 days",
  "contact.cta": "Call to book",
  "contact.cta2": "WhatsApp us",
  "footer.tag": "AC maintenance & repair · Hawalli, Kuwait"
}};

document.addEventListener("DOMContentLoaded", function () {
  var btn = document.getElementById("menuBtn");
  var nav = document.getElementById("mainNav");
  if (btn && nav) { btn.addEventListener("click", function () { nav.classList.toggle("open"); }); }
  nav && nav.querySelectorAll("a").forEach(function (a) { a.addEventListener("click", function () { nav.classList.remove("open"); }); });
  var dict = I18N.en || {};
  document.querySelectorAll("[data-i18n]").forEach(function (el) {
    var k = el.getAttribute("data-i18n");
    if (dict[k] !== undefined) { el.innerHTML = dict[k]; }
  });
});
